### ISSUE TITLE
能否为go1.23提供支持

### ISSUE THREAD

**Issue by JHue58** [fumiama/terasu#1]
在用go12.3构建zero-bot-plugin的时候发现link出错

**Comment by fumiama** [comment]
zbp本身就无法在>1.20下使用。不过1.23确实可以支持一下。

**Comment by JHue58** [comment]
> zbp本身就无法在>1.20下使用。不过1.23确实可以支持一下。

想问一下为什么无法使用呢？go的向下兼容做的还是很好的，是用到了大量的linkname？

**Comment by fumiama** [comment]
zbp依赖import顺序决定插件优先级，但是从1.20往上的版本这个顺序发生了变化，不再按用户导入的顺序，而是按字母顺序，导致优先级失效。

**Comment by JHue58** [comment]
> zbp依赖import顺序决定插件优先级，但是从1.20往上的版本这个顺序发生了变化，不再按用户导入的顺序，而是按字母顺序，导致优先级失效。

噢噢，了解了，谢谢
这边提一下和这个issuse无关的事，我看到zbp那边的gif插件也是您开发的，我在那边提了一个issuse能回复我一下吗[issues](https://github.com/FloatTech/ZeroBot-Plugin/issues/1044)
