### ISSUE TITLE
Go 1.23 引用本库后项目无法运行

### ISSUE THREAD

**Issue by lianhong2758** [fumiama/terasu#2]
Go版本:go version go1.23.1 windows/amd64
go.mod版本:go 1.22.0
引用的库:github.com/FloatTech/floatbox v0.0.0-20240505082030-226ec6713e14
运行go build后输出如下:
link: github.com/fumiama/terasu: invalid reference to crypto/tls.outBufPool

**Comment by fumiama** [comment]
See https://tip.golang.org/doc/go1.23

<img width="1188" alt="截屏2024-10-28 上午3 29 16" src="https://github.com/user-attachments/assets/b9d5d4a7-4cfa-4ddb-a6d8-abf0d8f067b9">

**Comment by fumiama** [comment]
更新到本库最新版并用`-ldflags=-checklinkname=0`编译。
