### ISSUE TITLE
Meets # rvcmd link: github.com/fumiama/terasu: invalid reference to crypto/tls.outBufPool during RVC-Models-Downloader $make

### ISSUE THREAD

**Issue by developerForSale** [fumiama/terasu#3]
I am building a desktop application that incorporates ChatTTS out of personal interest. 
I want users to know the exact progress of the model download instead of facing an endless rotating circle. So I attempted to redirect the console stdout from RVC-Models-Downloader, but some scripts prevented me from doing so. This happened before customize it to meet my requirement, just pull the code then $make it to ensure nothing special.
Any information or suggestion you can provide would be of great help to me.

```
RVC-Models-Downloader-for-VM$ go version
go version go1.23.2 linux/amd64

RVC-Models-Downloader-for-VM$ make
make[1]: Entering directory '/home/hjalty/Documents/work/projects/Go/RVC-Models-Downloader-for-VM'
  adding: assets/ (stored 0%)
  adding: assets/chtts.yaml (deflated 61%)
  adding: assets/hubert.yaml (deflated 16%)
  adding: assets/rmvpe.yaml (deflated 26%)
  adding: assets/rvc.yaml (deflated 29%)
  adding: assets/uvr5.yaml (deflated 56%)
  adding: assets/v1.yaml (deflated 65%)
  adding: assets/v2.yaml (deflated 66%)
# rvcmd
link: github.com/fumiama/terasu: invalid reference to crypto/tls.outBufPool
make[1]: *** [Makefile:14: bin] Error 1
make[1]: Leaving directory '/home/hjalty/Documents/work/projects/Go/RVC-Models-Downloader-for-VM'
make: *** [Makefile:12: all] Error 2
```

**Comment by developerForSale** [comment]
I tried the following:
- Downgrade Go version to 1.20.
- Update go.mod file version: `go mod edit -go 1.20`

Solve the problem! So it's somehow not supporting version 1.23 currently.

**Comment by fumiama** [comment]
Go 1.23 disabled outside linkname so this error will occur. Just to explain why, this library is designed for a special usage (bypass SNI blocking of GFW) that making sure the people in some region can access Hugging Face directly, in which linkname is necessary.
